### ISSUE TITLE
Doesn't detect nonstandard clients

### ISSUE THREAD

**Issue by ItzOasis** [Mr-Technician/BorderlessMinecraft#14]
I use Minecraft clients and it never detectest it like badloin or lunar

**Comment by ThatFlashCat** [comment]
I will look into this, thanks.

**Comment by gamingoninsulin** [comment]
it even it dont show up when played modded like ATM6 Sky trough curseforge and gd launcher ;)

**Comment by ThatFlashCat** [comment]
I'm going to make the process of selecting processes more lax in the future - probably just by accepting any Java process with a window. This means other Java applications can potentially show up in the list, but the best chance of working with any client.

**Comment by gamingoninsulin** [comment]
Maybe its possible to browes trough task manager thingy dialog to choose the right java aplication ? If you understand wat i mean

**Comment by Mr-Technician** [comment]
Fixed in [1.2.3](https://github.com/Mr-Technician/BorderlessMinecraft/releases/tag/v1.2.3).
