### ISSUE TITLE
Borderless Minecraft Crashes when MultiMC Instance Launched

### ISSUE THREAD

**Issue by swishkin** [Mr-Technician/BorderlessMinecraft#31]
The app (1.3.1) closes within a few seconds of launching my 1.17.1 instance in MultiMC, if "Automatic Borderless" is selected. I'd like for Borderless Minecraft to work automatically, but returning to manual mode prevents these crashes and allows successful borderless usage.

Is there anything I can provide (log, etc) to help debugging this?

**Comment by Mr-Technician** [comment]
That's a strange bug... If it provided some sort of crash report I would like to see it. @swishkin

**Comment by swishkin** [comment]
It closed without warning or any log/report that I saw; is there somewhere it'd put something like that?

**Comment by Mr-Technician** [comment]
I get a popup like this if I manually throw an exception: 
![image](https://user-images.githubusercontent.com/26885142/151617138-f0359a6c-18c9-4176-bdee-9bb3ad733762.png)

Since you don't get one I'm wondering if an exception isn't actually being thrown, but I'm not sure why borderless minecraft would crash otherwise.

How does your MultiMC instance of Minecraft show up in the task manager?

**Comment by swishkin** [comment]
Yes, it shows up as shown below:

![image](https://user-images.githubusercontent.com/19404743/151620739-167607ea-e7ad-4e5a-af04-b36d9ca74369.png)

**Comment by Mr-Technician** [comment]
Can you expand the Java process? Sorry for all the steps, I should have asked for that before. 😅

**Comment by swishkin** [comment]
Here you go!

![image](https://user-images.githubusercontent.com/19404743/151649426-40a43813-429e-4a3f-aab9-b7112ef6736c.png)

**Comment by cornerkey** [comment]
I Have exactly the same issue when automatic fullscreen is selected through multi mc

**Comment by cornerkey** [comment]
The path is different for multimc instances idk if that makes a difference

**Comment by Mr-Technician** [comment]
I'll need to install MultiMC and test with it so I can see what's going on...

I assume you don't get a crash report? @cornerkey

**Comment by cornerkey** [comment]
@Mr-Technician No i dont get a crash report it just straight up closes

**Comment by cornerkey** [comment]
it works if use normal launcher but i use multi mc because i speedrun and its easier to launch and maintain different instances

**Comment by Mr-Technician** [comment]
Ok, I will test with MultiMC if I get the chance. :)

**Comment by cornerkey** [comment]
ty u can ask me if u need assistance in any way

**Comment by Mr-Technician** [comment]
> ty u can ask me if u need assistance in any way

If you're feeling adventurous you can download the source code, run borderless minecraft from there, and see if an error comes up. :)

That requires Visual Studio though.

**Comment by Mr-Technician** [comment]
I've tracked down the bug. MultiMC does something weird that causes Borderless Minecraft to detect a java process that no longer exists, which throws an exception. I've added code to prevent this but need to debug some other odd behavior with automatic borderless before releasing it.

**Comment by Mr-Technician** [comment]
The other auto borderless issues appear to be resolved. I will clean the changes up tomorrow and release an update to fix this issue. 🚀

**Comment by cornerkey** [comment]
Thank you so much you were extremely helpful and you responded so quick, im really impressed.

**Comment by swishkin** [comment]
I really appreciate you looking into this and debugging it! I've switched to GDLauncher, and while it doesn't crash, it seems like it doesn't automatically borderless either. :/
