### ISSUE TITLE
Game lags when using borderless window + shaders

### ISSUE THREAD

**Issue by Slooshie1** [Mr-Technician/BorderlessMinecraft#32]
https://user-images.githubusercontent.com/90230538/152295045-7fe1cdff-64b0-4b3b-948c-6c497776c262.mp4

The game runs smoothly as usual until I zoom in using the Ok Zoomer mod. In normal fullscreen the mod has no problems zooming in and out, and neither does the windowed version. But as soon as I use borderless fullscreen it lags

**Comment by Mr-Technician** [comment]
I see your GPU usage spiked when you zoomed in. Could you send recordings in windowed and fullscreen for comparison?

**Comment by Slooshie1** [comment]
Not sure why, or how, but the zoom started to work normally in a borderless window.

The universe really is against me to make me look embarrassing haha. Every time I make an issue about an MC mod or program about a bug, it seems to always fix itself somehow. Sorry for any inconvenience, and I hope you have a good day/evening :)

Btw, would you still like me to send recordings of both windowed and fullscreen anyway?

**Comment by Mr-Technician** [comment]
Glad to hear that it's working now!

> Btw, would you still like me to send recordings of both windowed and fullscreen anyway?

That's up to you, it could potentially be helpful if the issue comes up again.

**Comment by Slooshie1** [comment]
> That's up to you, it could potentially be helpful if the issue comes up again.

Okay, I will record on windowed, full screen, and borderless to see if there are any differences. I am not currently at my computer, so I will do that in a short while

**Comment by Slooshie1** [comment]
https://user-images.githubusercontent.com/90230538/152474352-aae481f6-77af-4601-b48e-e93ded423a15.mp4

The lagging problem came back, but I was not even using zoom this time. I don't think this program likes shaders. Interestingly, MSI Afterburner says my framerate is pretty normal but the screen suggests otherwise. I record in fullscreen at first then switch to borderless.

**Comment by Slooshie1** [comment]
Okay. I tried WinExplorer and that also makes me lag. I think my computer hates running games in borderless windows because it also lags with Roblox + ReShade (Roblox does not have an actual fullscreen mode, it uses borderless windowed). My drivers are all up to date so I'm not sure what may be causing this. I'm really disappointed because I like playing in borderless fullscreen but my computer just does not like doing that at all so I think I'll just have to live with native fullscreen options :(

**Comment by Mr-Technician** [comment]
It's odd that it doesn't happen in windowed mode but does happen in borderless... However fullscreen can perform differently than any windowed mode.
