### ISSUE TITLE
Start minimized when start on boot is turned off

### ISSUE THREAD

**Issue by miapuffia** [Mr-Technician/BorderlessMinecraft#40]
I'd like start minimized to start the application minimized even when start on boot is turned off. An extra setting for this would be fine as well. If this can't be done, I think start minimized should be disabled (greyed out) when start on boot is turned off.
Thanks

**Comment by Mr-Technician** [comment]
Good idea, I think either alternative would work but there's no reason the application can't start minimized when start on boot is disabled.

I am not sure when I will get to this but thanks for the feedback. :)

**Comment by miapuffia** [comment]
Great. I'll take a look and see if I can't put a pull request in to add this functionality

**Comment by Mr-Technician** [comment]
PRs are always appreciated! :)

I may also get a website up for the project, eventually. 😅

**Comment by miapuffia** [comment]
PR submitted. I have some web development experience if you'd like me to help whip up something simple.

**Comment by Mr-Technician** [comment]
I actually started playing around with blazor and did create a website, however I wasn't happy with how it turned out and finishing it wasn't a high priority: https://borderlessminecraft.com/

**Comment by Mr-Technician** [comment]
Fixed in #42.
